default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manga_project_development
  username: carloz
  password: carloz96

test:
  <<: *default
  database: manga_project_test
  username: carloz
  password: carloz96

production:
  <<: *default
  database: manga_project_production
  username: carloz
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>
