default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manga_project_development
  username: carloz
  password: carloz96

test:
  <<: *default
  database: manga_project_test
  username: carloz
  password: carloz96

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSERNAME'] %>
  password: <%= ENV['PGPASSWORD'] %>
  port: 5432
